on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: Install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm install
      - run: node scripts/update-releases.js
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@3d1b5e078a85df99db0cb2441cd4309b09d86253
        with:
          commit_message: update releases
          file_pattern: content/releases
